export enum ACTIONS {
  INCREMENT ="INCREMENT",
  DECREMENT ="DECREMENT",
  CHANGED_SELECTED_SERVICE="CHANGED_SELECTED_SERVICE",
  CHANGED_SELECTED_SERVICE_BY_TAG="CHANGED_SELECTED_SERVICE_BY_TAG",
  CHANGE_TOGGLE="CHANGE_TOGGLE",
  FETCH_USER_LOADING="FETCH_USER_LOADING",
  FETCH_USER_SUCCESS="FETCH_USER_SUCCESS",
  FETCH_USER_ERROR="FETCH_USER_ERROR",
  FETCH_ALL_USERS_SUCCESS="FETCH_ALL_USERS_SUCCESS"
}


